apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-app
  template:
    metadata:
      labels:
        app: rest-app
    spec:
      containers:
      - name: rest-app
        image: rest-app:1.1
        ports:
        - containerPort: 8181
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: rest-nginx-conf-vol
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: rest-nginx-conf-vol
        configMap:
          name: rest-nginx-conf
