apiVersion: v1
kind: Service
metadata:
  name: rest-app
spec:
  selector:
    app: rest-app
  ports:
    - name: rest-app
      protocol: TCP
      port: 8181
      targetPort: 8181
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
