apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.jenkins.appName }}
    namespace: {{ .Values.namespace }}
spec:
    replicas: {{ .Values.jenkins.replicas }}
    selector:
       matchLabels:
          app: {{ .Values.jenkins.app }}		
    template:
       metadata:
           labels:
               app: {{ .Values.jenkins.app }}
       spec:
           containers:
              - name: {{ .Values.jenkins.app }}
                image: {{ .Values.jenkins.image }}
                ports:
                - containerPort: {{ .Values.jenkins.containerPort }}
                volumeMounts:
                     - name: {{ .Values.pv.name }}
                       mountPath: {{ .Values.pv.mountPath }}
           volumes:
               - name: {{ .Values.pv.name }}
                 hostPath:
                      path: {{ .Values.pv.path }}
                      type: DirectoryOrCreate


---

apiVersion: v1
kind: Service
metadata:
   name: {{ .Values.service.name }}
spec:
   selector:
          app: {{ .Values.jenkins.app }}
   type: {{ .Values.service.type }}
   ports:
   - port: {{ .Values.service.port }}
     nodePort: {{ .Values.service.nodePort }}
     targetPort: {{ .Values.service.targetPort }}
       
       

