apiVersion: apps/v1
kind: Deployment
metadata: 
  name: python-flask
  namespace: ci
  labels:
    app: testapp
spec:
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: python-flask
          image: hassandocker1/docker-test:21
