apiVersion: v1
kind: Service
metadata:
  name: python-flask
  namespace: ci
  labels:
    app: python-flask
spec:
  selector:
    app: test-app
  type: NodePort
  ports:
    - name: http
      #targetPort: 8181
      port: 8181


